version: '3.9'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo_container
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - ./mongo-data/:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express_container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongo:27017/?authSource=${MONGO_DB_AUTH_SOURCE}
    depends_on:
      - mongo

  app:
    image: dimpap/app:0.0.7
    container_name: app_container
    restart: always
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
